name: Self-Hosted Code Analysis

on:
  push:
    branches: [main]
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install bandit

      - name: Run Bandit
        run: |
          bandit -r src/ -f json -o bandit.json

      - name: Start SonarQube Docker container
        run: |
          docker run -d --name sonarqube \
            -p 9000:9000 \
            -e SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true \
            sonarqube:9.9-community

      - name: Wait for SonarQube to be healthy
        run: |
          echo "Waiting for SonarQube..."
          until curl -s http://localhost:9000/api/system/health | grep -q '"status":"GREEN"'; do
            sleep 5
          done

      - name: Download and configure SonarScanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner-cli-*.zip
          echo "$PWD/sonar-scanner-*/bin" >> $GITHUB_PATH

      - name: Run SonarQube scan
        env:
          SONAR_HOST_URL: "http://localhost:9000"
          SONAR_TOKEN: "admin"
        run: |
          sonar-scanner \
            -Dsonar.projectKey=my-python-project \
            -Dsonar.sources=src \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.qualitygate.wait=true

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Generate Sonar Scan Report
        env:
          SONAR_TOKEN: "admin"
        run: |
          SONAR_API="http://localhost:9000/api"
          PROJECT_KEY="my-python-project"

          curl -s -u "${SONAR_TOKEN}:" \
              "${SONAR_API}/issues/search?componentKeys=${PROJECT_KEY}&ps=500" \
              -o "issues.json"

          curl -s -u "${SONAR_TOKEN}:" \
              "${SONAR_API}/qualitygates/project_status?projectKey=${PROJECT_KEY}" \
              -o "quality_gate.json"

          curl -s -u "${SONAR_TOKEN}:" \
              "${SONAR_API}/measures/component?component=${PROJECT_KEY}&metricKeys=coverage,line_coverage,duplicated_lines_density,ncloc,complexity" \
              -o "measures.json"

          jq -s '{
            timestamp: now,
            issues: .[0].issues,
            quality_gate: .[1].projectStatus,
            metrics: .[2].component.measures
          }' issues.json quality_gate.json measures.json > sonar.json

      - name: Upload Sonar report
        uses: actions/upload-artifact@v4
        with:
          name: sonar-json-report
          path: sonar.json

      - name: Upload Bandit report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit.json

      - name: Stop SonarQube container
        if: always()
        run: |
          docker stop sonarqube && docker rm sonarqube
